# Exploring the functionalities of Tensorflow funcs

## Importing libraries

In [1]:
import tensorflow as tf

- First we will define a simple func to calcualte the cube of a no.

In [2]:
def cube(x):
    return x ** 3

- We can call this func with a python value such a an int or float or a tensor.

In [3]:
cube(2)

8

In [4]:
cube(tf.constant(2.))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

- Now use tf.function() to convert this func into a tensorflow func.

In [5]:
tf_cube = tf.function(cube)

In [6]:
tf_cube

- This func can be used in the same way as the python func and it will return the same values but as tensors.

In [8]:
tf_cube(2.)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [9]:
tf_cube(tf.constant(2.))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

- Under the hood the TF func analyzes the computations performed by the python func and generates an equivalent computation graph.
- Alternatively we can also use tf.function as a decorator which is more common.

In [33]:
@tf.function
def tf_cube(x):
    return x ** 3

- The original python func is still available via the python_function() attribute

In [34]:
tf_cube.python_function(2.)

8.0

### TF Functions and concrete functions

In [22]:
concrete_function = tf_cube.get_concrete_function(tf.constant(2.))

In [23]:
concrete_function.graph

In [24]:
concrete_function(tf.constant(2.))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [25]:
concrete_function is tf_cube.get_concrete_function(2.)

False

## Exploring func definitions and graphs

In [27]:
concrete_function.graph

In [28]:
ops = concrete_function.graph.get_operations()

In [29]:
ops

[<tf.Operation 'x' type=Placeholder>,
 <tf.Operation 'pow/y' type=Const>,
 <tf.Operation 'pow' type=Pow>,
 <tf.Operation 'Identity' type=Identity>]

In [31]:
pow_op = ops[2]

In [32]:
pow_op.inputs

(<tf.Tensor 'x:0' shape=() dtype=float32>,
 <tf.Tensor 'pow/y:0' shape=() dtype=float32>)